### ISSUE TITLE
路由重复动态录入

### ISSUE THREAD

**Issue by yiwuyu** [tower1229/Vue-Access-Control#2]
您好
在App.vue模块的extendRoute方法
如果未刷新岂不是重复addRoutes了吗

**Comment by tower1229** [comment]
感谢反馈，确实是重复addRoutes了，对于重复的路由vue-router自身会过滤掉，但可能导致的一个权限问题是，先后登录的不同角色可以手动访问对方的路由。
目前该bug已经修复，修复方案是为动态路由添加独享守卫，当用户越权访问时将跳转401公共页面。

**Comment by yiwuyu** [comment]
假设
A有 {a,b}路由页
B有 {b,c}路由页
退出A之后登陆B，我发现除了报重复录入，c并没有被addRoutes进去，仍然报的404
最后我只能在登陆的时候用window.location.href来跳转 而不是用router.push

**Comment by tower1229** [comment]
@yiwuyu addRoutes肯定是生效的，但addRoutes的时候要把404页面放在数组最后再添加一次，否则后添加的路由不会被匹配到

**Comment by warmilk** [comment]
求app.vue的详细注释

**Comment by tower1229** [comment]
@warmilk 添加了部分注释，不知道还能怎么详细了

**Comment by warmilk** [comment]
![image](https://user-images.githubusercontent.com/14016918/34930186-4d0a92fc-fa03-11e7-91c9-76cfdddde092.png)
其实不是很明白这里的getPermission函数是用来干嘛的···
看了下userInfo对应的实参，没看到有userInfo.resources啊···要懵圈了
![image](https://user-images.githubusercontent.com/14016918/34930251-a2ced2ca-fa03-11e7-8844-81c966cbabda.png)

**Comment by warmilk** [comment]
暂时的理解是，通过后台signin接口返回的menus字段，前端处理得到当前用户有权访问的路由的name数组，然后用这个name数组去 _.filter 出最终要展示的路由？

通过name数组去过滤得到最终路由对象数组的过程，我能不能直接用 Lodash 的 Collection 相关的API呢？

主要是这几个函数有些涉及到正则，看得一脸懵逼，不太理解它们是怎么相互调用的 QAQ 大神有空求解答
![image](https://user-images.githubusercontent.com/14016918/34930653-7ff532d8-fa05-11e7-9fcc-231a0f744c38.png)

**Comment by tower1229** [comment]
@warmilk getPermission()方法是用来将后台返回的资源权限数据转成对象格式，userInfo.resources就在你截图里能找到啊，menus下面就是resources。
你理解的思路是对的 ，所有这些方法你都可以自己重新实现。只要最终拿到实际路由就可以完成路由权限控制；只要能利用资源权限实现出来一个权限校验方法，就能实现任意界面的任何权限控制。

**Comment by warmilk** [comment]
乌龙了眼瞎没看到orz，有resources字段之后权限控制的粒度就更细了，大概能理解鸟，谢谢大神

**Comment by warmilk** [comment]
![image](https://user-images.githubusercontent.com/14016918/35023026-d995862a-fb73-11e7-8528-a5a88cb98568.png)
@tower1229  大大求问这里的ckey形参是用来干嘛的 QAQ

**Comment by tower1229** [comment]
@warmilk 这个方法用来将一维数组按照元素之间的父子关系转成多维数组，这个ckey就是用来自定义父元素id字段的，默认父元素id存在“parent_id”里，但有的数据可能存在其他字段里，所有加了这样一个参数。

**Comment by warmilk** [comment]
@tower1229  已经能实现动态路由的注入了，谢谢大神~

但是今天遇到了一个头痛的问题，浏览器有缓存 ····

 比如后台账号A，有1,2,3,4,5菜单权限，后台账号B，只有1,2,3菜单权限，

本地测试先登录A后登录B的话，菜单4,5由于缓存账号B也是能访问到的···

在账号B点击菜单4,5时，要手动 ctrl+F5 强制刷新才能自动跳转401页，有什么比较优雅的解决方案吗QAQ

感觉禁止缓存太粗暴了···

**Comment by tower1229** [comment]
@warmilk 切换用户时应该修改请求头里的token信息了，这样就不会有缓存了，如果你们是在服务端session里保持用户状态，确实会有缓存问题，貌似除了禁止缓存就没有其他办法了吧。

**Comment by ZTFtrue** [comment]
退出不登录依然可以手动访问

**Comment by ZTFtrue** [comment]
退出时刷新是更好的办法。
@tower1229  
```js
   this.$router.replace({path: '/login'});
   window.history.go(0);
```
我在退出页面做了处理，退出时清理session，退出页面没有session就会回到登录页面

**Comment by tower1229** [comment]
@ZTFtrue 退出还可以手动访问的问题修复了，现在退出后将清除路由权限和请求权限，效果跟刷新一样。

**Comment by 13311282556** [comment]
新手，需要做权限控制，看的一脸的懵逼，不知道从何看起，从开始的
![image](https://user-images.githubusercontent.com/10527922/44835273-4f303080-ac66-11e8-9647-cccfb9ec5d2f.png)就开始看不明白了，后来的公共路由是怎么引用的?

**Comment by tower1229** [comment]
@zhangxlgj 退出不刷新也可以的，清除掉本地登录凭证就可以了。路由没有清除的方法，重复路由不影响前台展示，所有路由也都加了单独的守卫，即便应用内存在的路由也无法越权访问，应该没什么问题了吧
