### ISSUE TITLE
rap2api.taobao.org的请求失效

### ISSUE THREAD

**Issue by Roqii** [tower1229/Vue-Access-Control#5]
这几天刚好在做权限控制，开发中突然请求都是500码，然后过了一晚，请求就不可用了。

get:
http://rap2api.taobao.org/app/mock/224/GET/web?name=root&password=MQ%3D%3D
Response:
{"isOk":false,"errMsg":"未匹配到任何接口 No matched interface"}

**Comment by tower1229** [comment]
好了，rap2偷偷摸摸的修复了一个bug，导致url规则改变了

**Comment by acid122** [comment]
> 好了，rap2偷偷摸摸的修复了一个bug，导致url规则改变了
接口又不能用了，有接口返回文档吗，可以模拟一下

**Comment by tower1229** [comment]
> > 好了，rap2偷偷摸摸的修复了一个bug，导致url规则改变了
> > 接口又不能用了，有接口返回文档吗，可以模拟一下

在rap2上搜所有仓库，关键词：Vue-Access-Control，能搜到

**Comment by acid122** [comment]
> > > 好了，rap2偷偷摸摸的修复了一个bug，导致url规则改变了
> > > 接口又不能用了，有接口返回文档吗，可以模拟一下
> 
> 在rap2上搜所有仓库，关键词：Vue-Access-Control，能搜到

谢谢，但是发现最近rap2注册登录不起了，感觉rap2系统不太稳定的，目前还未搜到

**Comment by tower1229** [comment]
> > > > 好了，rap2偷偷摸摸的修复了一个bug，导致url规则改变了
> > > > 接口又不能用了，有接口返回文档吗，可以模拟一下
> > 
> > 
> > 在rap2上搜所有仓库，关键词：Vue-Access-Control，能搜到
> 
> 谢谢，但是发现最近rap2注册登录不起了，感觉rap2系统不太稳定的，目前还未搜到

导出到postman的链接：http://rap2api.taobao.org/postman/export?id=224
