### ISSUE TITLE
服务端直接返回所有的路由权限list ,是由于网上其他那种自己filter对应权限的做法。

### ISSUE THREAD

**Issue by william-xue** [tower1229/Vue-Access-Control#6]
如果后续要添加权限角色的话 后者需要前端路由一个一个的不断添加。

**Comment by william-xue** [comment]
我是区分于网上另一种的 https://segmentfault.com/a/1190000009506097。感觉你的处理方法更好

**Comment by tower1229** [comment]
我的方案理论上已经达到权限控制的最小颗粒度，是最灵活的方式，代价是前后端需要约定权限数据格式。
